server:
  port: 8080

spring:
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.MySQLDialect
      "[hibernate.generate.statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  flyway:
    url: ${mysql.url:jdbc:mysql://localhost:3306/ProductDetails?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    user: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    enabled: false

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cache:
    type: redis
  data:

    redis:
      host: ${redis.url:localhost}
      port: ${redis.port:6379}

  datasource:
    url: ${mysql.url:jdbc:mysql://localhost:3306/ProductDetails?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: master

  batch:
    jdbc:
      initialize-schema: "always"
    job:
      enabled: false


